{% set version = "3.2" %}

package:
  name: vtkbool
  version: {{ version }}

source:
  url: https://github.com/zippy84/vtkbool/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f8af7ecaf8ec20fefb3e3c1fe7e84490d07bd5eee89a26564424059f2bfc2eb3
  patches:
    - modify-cmakelists.patch  # patch cmakelists to support building in conda env

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vtkbool', max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - python
    - vtk
  run:
    - python
    - vtk

test:
  commands:
    - test -f $PREFIX/include/vtkBoolModule.h     # [unix]
    - test -f $PREFIX/lib/libvtkBool${SHLIB_EXT}  # [unix]
  imports:
    - vtkbool
    - vtkbool.vtkbool

about:
  home: https://github.com/zippy84/vtkbool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A VTK-based library for boolean operations on polygonal meshes.
  description: |
    vtkbool is a library for boolean operations on polygonal meshes,
    based on VTK. vtkbool is developed by by Ronald Römer (@zippy84).
  doc_url: https://github.com/zippy84/vtkbool/blob/master/README.md
  dev_url: https://github.com/zippy84/vtkbool

extra:
  recipe-maintainers:
    - whophil
    - akaszynski
