{% set version = "2.9.5" %}

package:
  name: vtkbool
  version: {{ version }}

source:
  url: https://github.com/zippy84/vtkbool/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2b197792f5033f06767574fe1129088a40657eab79e238c25d8aa515e960e067
  patches:
    - modify-cmakelists.patch  # patch cmakelists to support building in conda env

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('vtkbool', max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  host:
    - python
    - vtk-base
  run:
    - python
    - vtk-base

test:
  commands:
    - test -f $PREFIX/include/vtkBoolModule.h     # [unix]
    - test -f $PREFIX/lib/libvtkBool${SHLIB_EXT}  # [unix]
  imports:
    - vtkbool
    - vtkbool.vtkBool

about:
  home: https://github.com/zippy84/vtkbool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A VTK-based library for boolean operations on polygonal meshes.
  description: |
    vtkbool is a library for boolean operations on polygonal meshes,
    based on VTK. vtkbool is developed by by Ronald Römer (@zippy84).
  doc_url: https://github.com/zippy84/vtkbool/blob/master/README.md
  dev_url: https://github.com/zippy84/vtkbool

extra:
  recipe-maintainers:
    - whophil
    - akaszynski
